# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_plate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Plate(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(287, 227)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_plateLength = QtWidgets.QLineEdit(Dialog)
        self.txt_plateLength.setObjectName("txt_plateLength")
        self.gridLayout.addWidget(self.txt_plateLength, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txt_plateWidth = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateWidth.setFont(font)
        self.txt_plateWidth.setReadOnly(True)
        self.txt_plateWidth.setObjectName("txt_plateWidth")
        self.gridLayout.addWidget(self.txt_plateWidth, 1, 1, 1, 1)
        self.txt_plateHeight = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateHeight.setFont(font)
        self.txt_plateHeight.setReadOnly(True)
        self.txt_plateHeight.setObjectName("txt_plateHeight")
        self.gridLayout.addWidget(self.txt_plateHeight, 0, 1, 1, 1)
        self.txt_plateThickness = QtWidgets.QLineEdit(Dialog)
        self.txt_plateThickness.setObjectName("txt_plateThickness")
        self.gridLayout.addWidget(self.txt_plateThickness, 4, 1, 1, 1)
        self.plateHeight = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plateHeight.setFont(font)
        self.plateHeight.setObjectName("plateHeight")
        self.gridLayout.addWidget(self.plateHeight, 0, 0, 1, 1)
        self.txt_plateno = QtWidgets.QLineEdit(Dialog)
        self.txt_plateno.setObjectName("txt_plateno")
        self.gridLayout.addWidget(self.txt_plateno, 2, 1, 1, 1)
        self.txt_filletWeldSize = QtWidgets.QLineEdit(Dialog)
        self.txt_filletWeldSize.setObjectName("txt_filletWeldSize")
        self.gridLayout.addWidget(self.txt_filletWeldSize, 5, 1, 1, 1)
        self.txt_NotchSize = QtWidgets.QLineEdit(Dialog)
        self.txt_NotchSize.setObjectName("txt_NotchSize")
        self.gridLayout.addWidget(self.txt_NotchSize, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Plate"))
        self.label_2.setText(_translate("Dialog", "Width (mm)"))
        self.plateHeight.setText(_translate("Dialog", "Height (mm)"))
        self.label.setText(_translate("Dialog", "Number"))
        self.label_3.setText(_translate("Dialog", "Length"))
        self.label_4.setText(_translate("Dialog", "Thickness"))
        self.label_5.setText(_translate("Dialog", "Fillet Weld Size"))
        self.label_6.setText(_translate("Dialog", "Notch Size"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

